; PlatformIO Project Configuration File
;
; Analog-Input-with-Potentiometer-and-PWM
; ESP32-S3 DevKitC-1 — Potentiometer-controlled LED brightness via PWM
;
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
